## 1. 이미지 변환

In [1]:
import numpy as np
import cv2

In [2]:
# 이미지 사이즈 조정

def transform():
    img = cv2.imread('images/movie_image.jpg')
    h, w = img.shape[:2]
    
    img2 = cv2.resize(img, None, fx=0.5, fy=1, interpolation=cv2.INTER_AREA)
    img3 = cv2.resize(img, None, fx=1, fy=0.5, interpolation=cv2.INTER_AREA)
    img4 = cv2.resize(img, None, fx=0.5, fy=0.5, interpolation=cv2.INTER_AREA)
    
    cv2.imshow('original', img)
    cv2.imshow('fx=0.5', img2)
    cv2.imshow('fy=0.5', img3)
    cv2.imshow('fx=0.5, fy=0.5', img4)
    
    cv2.waitKey(0)
    cv2.destroyAllWindows()
    
transform()

In [4]:
# 이미지 이동

def transform():
    img = cv2.imread('images/model.png')
    h, w = img.shape[:2]
    
    M = np.float32([[1, 0, 100], [0, 1, 50]])
    
    img2 = cv2.warpAffine(img, M, (w,h))
    cv2.imshow('shift image', img2)
    
    cv2.waitKey(0)
    cv2.destroyAllWindows()
    
transform()

In [5]:
# 이미지 회전

def transform():
    img = cv2.imread('images/model.png')
    h, w = img.shape[:2]
    
    M1 = cv2.getRotationMatrix2D((w/2, h/2), 45, 1)
    M2 = cv2.getRotationMatrix2D((w/2, h/2), 90, 1)
    
    img2 = cv2.warpAffine(img, M1, (w,h))
    img3 = cv2.warpAffine(img, M2, (w,h))
    
    cv2.imshow('45-Rotated', img2)
    cv2.imshow('90-Rotated', img3)
    
    cv2.waitKey(0)
    cv2.destroyAllWindows()
    
transform()

In [6]:
# 이미지 원근 보정

def transform():
    img = cv2.imread('images/model.png')
    h, w = img.shape[:2]
    
    pts1 = np.float32([[50,50], [200,50], [20,200]])
    pts2 = np.float32([[10,100], [200, 50], [100, 250]])
    
    M = cv2.getAffineTransform(pts1, pts2)
    
    img2 = cv2.warpAffine(img, M, (w,h))
    
    cv2.imshow('original', img)
    cv2.imshow('Affine-Transform', img2)
    
    cv2.waitKey(0)
    cv2.destroyAllWindows()
    
transform()    

In [14]:
def transform():
    img = cv2.imread('images/model.png')
    h, w = img.shape[:2]
    
    pts1 = np.float32([[0,0], [300, 0], [0, 300], [300,300]])
    pts2 = np.float32([[56,65], [368, 52], [28, 387], [389,390]])
    
    M = cv2.getPerspectiveTransform(pts1, pts2)
    
    img2 = cv2.warpPerspective(img, M, (w,h))
    
    cv2.imshow('original', img)
    cv2.imshow('Perspective-Transform', img2)
    
    cv2.waitKey(0)
    cv2.destroyAllWindows()
    
transform()

## 2. 이미지 블러

In [15]:
def bluring():
    img = cv2.imread('images/model.png')
    
    kernel = np.ones((5,5), np.float32)/25
    blur = cv2.filter2D(img, -1, kernel)
    
    cv2.imshow('original', img)
    cv2.imshow('blur', blur)
    
    cv2.waitKey(0)
    cv2.destroyAllWindows()
    
bluring()

In [19]:
def onMouse(x):
    pass

def bluring():
    img = cv2.imread('images/model.png')
    
    cv2.namedWindow('BlurPane')
    cv2.createTrackbar('BLUR_MODE', 'BlurPane', 0, 2, onMouse)
    cv2.createTrackbar('BLUR', 'BlurPane', 0, 5, onMouse)
    
    mode = cv2.getTrackbarPos('BLUR_MODE', 'BlurPane')
    val = cv2.getTrackbarPos('BLUR', 'BlurPane')
    
    while True:
        val = val*2 + 1
        
        try:
            if mode == 0:
                blur = cv2.blur(img, (val, val)) # val -> 블러처리할 커널 사이즈
            elif mode == 1:
                blur = cv2.GaussianBlur(img, (val, val), 0) # 가우스 노이즈 제거에 특화(edge 보존이 안됨)
            elif mode == 2:
                blur = cv2.medianBlur(img, val) # 소금후추 노이즈 제거 특화
            else:
                break
                
            cv2.imshow('BlurPane', blur)
        except:
            break
            
        k = cv2.waitKey(1) & 0xFF
        if k == 27:
            break
            
        mode = cv2.getTrackbarPos('BLUR_MODE', 'BlurPane')
        val = cv2.getTrackbarPos('BLUR', 'BlurPane')
        
    cv2.destroyAllWindows()
    
bluring()

## 3. 이미지 Erosion & Dilation

![image](images/Erosion_1.PNG)
![image](images/Erosion_2.PNG)

In [25]:
def morph():
    img = cv2.imread('images/word.PNG', cv2.IMREAD_GRAYSCALE)
    
    kernel = np.ones((3,3), np.uint8)

    erosion = cv2.erode(img, kernel, iterations=1)
    dilation = cv2.dilate(img, kernel, iterations=1)
    
    cv2.imshow('original', img)
    cv2.imshow('ersoion', erosion)
    cv2.imshow('dilation', dilation)
    
    cv2.waitKey(0)
    cv2.destroyAllWindows()
    
morph()

In [30]:
# opening : erosion을 수행 이후 dilation를 곧바로 수행
# closing : dilation을 수행 이후 erosion를 곧바로 수행

def morph():
    img1 = cv2.imread('images/opening.PNG', cv2.IMREAD_GRAYSCALE)
    img2 = cv2.imread('images/closing.PNG', cv2.IMREAD_GRAYSCALE)
    
    kernel = np.ones((5,5), np.uint8)
    
    opening = cv2.morphologyEx(img1, cv2.MORPH_OPEN, kernel) # opening
    closing = cv2.morphologyEx(img2, cv2.MORPH_CLOSE, kernel) # closing
    
    cv2.imshow('opening', opening)
    cv2.imshow('closing', closing)
    
    cv2.waitKey(0)
    cv2.destroyAllWindows()
    
morph()

In [32]:
# GRADIENT : Dilation 이미지와 Erosion 이미지의 차이
# TOPHAT : 원본이미지와 opening한 이미지의 차이
# BLACKHAT : closing한 이미지와 원본이미지의 차이

def morph():
    img1 = cv2.imread('images/word.PNG', cv2.IMREAD_GRAYSCALE)
    img2 = cv2.imread('images/opening.PNG', cv2.IMREAD_GRAYSCALE)
    img3 = cv2.imread('images/closing.PNG', cv2.IMREAD_GRAYSCALE)
    
    kernel = np.ones((3,3), np.uint8)
    
    grad = cv2.morphologyEx(img1, cv2.MORPH_GRADIENT, kernel)
    tophat = cv2.morphologyEx(img2, cv2.MORPH_TOPHAT, kernel)
    blackhat = cv2.morphologyEx(img3, cv2.MORPH_BLACKHAT, kernel)
    
    cv2.imshow('grad', grad)
    cv2.imshow('tophat', tophat)
    cv2.imshow('blackhat', blackhat)
    
    cv2.waitKey(0)
    cv2.destroyAllWindows()
    
morph()

## 3. 커널 매트릭스 생산

In [34]:
def makeKernel():
    M1 = cv2.getStructuringElement(cv2.MORPH_RECT, (5, 5))
    M2 = cv2.getStructuringElement(cv2.MORPH_ELLIPSE, (5, 5))
    M3 = cv2.getStructuringElement(cv2.MORPH_CROSS, (5, 5))
    
    print(M1)
    print(M2)
    print(M3)
    
makeKernel()

[[1 1 1 1 1]
 [1 1 1 1 1]
 [1 1 1 1 1]
 [1 1 1 1 1]
 [1 1 1 1 1]]
[[0 0 1 0 0]
 [1 1 1 1 1]
 [1 1 1 1 1]
 [1 1 1 1 1]
 [0 0 1 0 0]]
[[0 0 1 0 0]
 [0 0 1 0 0]
 [1 1 1 1 1]
 [0 0 1 0 0]
 [0 0 1 0 0]]
